server:
  port: 2221

spring:
  application:
    name: eureka-provider

eureka:
  instance:
    hostname: localhost
# 使用ip地址代替localhost访问服务
#    prefer-ip-address: true
# 将注册列表中的服务实例名称换为ip地址，注意：向自身注册时需要开启defaultZone配置
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 10 # 续约到期时间（默认90秒）,开发阶段设置短一些
    lease-renewal-interval-in-seconds: 5 # 续约更新时间间隔（默认30秒）,开发阶段设置短一些
  client:
# 单服务注册中心时使用
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
# 集群情况使用，注册到所有注册中心，包括自己
#      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/
