server:
  port: 6661

spring:
  application:
    name: eureka-consumer-ribbon-hystrix

eureka:
  instance:
    hostname: localhost
# 使用ip地址代替localhost访问服务
#    prefer-ip-address: true
# 将注册列表中的服务实例名称换为ip地址，注意：向自身注册时需要开启defaultZone配置
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
